src/sourcinasia/appBundle/Entity/User.php
<?php

namespace sourcinasia\appBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * User
 */
class User extends BaseUser {

    /**
     * @var integer
     */
    protected $id;

    /**
     * @var \sourcinasia\appBundle\Entity\Contact
     */
    private $contact;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $histories;

    /**
     * @var \sourcinasia\appBundle\Entity\Logo
     */
    private $logo;

    /**
     * @var integer
     */
    private $modeonlogin;

    /**
     * @var string
     */
    private $locale;

    /**
     * @var integer
     */
    private $customermargecoef;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $domainerestriction;

    /**
     * Constructor
     */
    public function __construct() {
        parent::__construct();
        $this->histories = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set contact
     *
     * @param \sourcinasia\appBundle\Entity\Contact $contact
     * @return User
     */
    public function setContact(\sourcinasia\appBundle\Entity\Contact $contact = null) {
        $this->contact = $contact;

        return $this;
    }

    /**
     * Get contact
     *
     * @return \sourcinasia\appBundle\Entity\Contact 
     */
    public function getContact() {
        return $this->contact;
    }

    /**
     * Set logo
     *
     * @param \sourcinasia\appBundle\Entity\Logo $logo
     * @return User
     */
    public function setLogo(\sourcinasia\appBundle\Entity\Logo $logo = null) {
        $this->logo = $logo;

        return $this;
    }

    /**
     * Get logo
     *
     * @return \sourcinasia\appBundle\Entity\Logo 
     */
    public function getLogo() {
        return $this->logo;
    }

    /**
     * Set modeonlogin
     *
     * @param integer $modeonlogin
     * @return User
     */
    public function setModeonlogin($modeonlogin) {
        $this->modeonlogin = $modeonlogin;

        return $this;
    }

    /**
     * Get modeonlogin
     *
     * @return integer 
     */
    public function getModeonlogin() {
        return $this->modeonlogin;
    }

    /**
     * Set locale
     *
     * @param string $locale
     * @return User
     */
    public function setLocale($locale) {
        $this->locale = $locale;

        return $this;
    }

    /**
     * Get locale
     *
     * @return string 
     */
    public function getLocale() {
        return $this->locale;
    }

    /**
     * Set customermargecoef
     *
     * @param integer $customermargecoef
     * @return User
     */
    public function setCustomermargecoef($customermargecoef) {
        $this->customermargecoef = $customermargecoef;

        return $this;
    }

    /**
     * Get customermargecoef
     *
     * @return integer 
     */
    public function getCustomermargecoef() {
        return $this->customermargecoef;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return User
     */
    public function setName($name) {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Set domainerestriction
     *
     * @param string $domainerestriction
     * @return User
     */
    public function setDomainerestriction($domainerestriction) {
        $this->domainerestriction = $domainerestriction;

        return $this;
    }

    /**
     * Get domainerestriction
     *
     * @return string 
     */
    public function getDomainerestriction() {
        return $this->domainerestriction;
    }


    /**
     * Add histories
     *
     * @param \sourcinasia\appBundle\Entity\History $histories
     * @return User
     */
    public function addHistory(\sourcinasia\appBundle\Entity\History $histories)
    {
        $this->histories[] = $histories;

        return $this;
    }

    /**
     * Remove histories
     *
     * @param \sourcinasia\appBundle\Entity\History $histories
     */
    public function removeHistory(\sourcinasia\appBundle\Entity\History $histories)
    {
        $this->histories->removeElement($histories);
    }

    /**
     * Get histories
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getHistories()
    {
        return $this->histories;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $cadenciers;


    /**
     * Add cadenciers
     *
     * @param \sourcinasia\appBundle\Entity\Cadencier $cadenciers
     * @return User
     */
    public function addCadencier(\sourcinasia\appBundle\Entity\Cadencier $cadenciers)
    {
        $this->cadenciers[] = $cadenciers;

        return $this;
    }

    /**
     * Remove cadenciers
     *
     * @param \sourcinasia\appBundle\Entity\Cadencier $cadenciers
     */
    public function removeCadencier(\sourcinasia\appBundle\Entity\Cadencier $cadenciers)
    {
        $this->cadenciers->removeElement($cadenciers);
    }

    /**
     * Get cadenciers
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCadenciers()
    {
        return $this->cadenciers;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $useractivities;


    /**
     * Add useractivities
     *
     * @param \sourcinasia\appBundle\Entity\Useractivity $useractivities
     * @return User
     */
    public function addUseractivity(\sourcinasia\appBundle\Entity\Useractivity $useractivities)
    {
        $this->useractivities[] = $useractivities;

        return $this;
    }

    /**
     * Remove useractivities
     *
     * @param \sourcinasia\appBundle\Entity\Useractivity $useractivities
     */
    public function removeUseractivity(\sourcinasia\appBundle\Entity\Useractivity $useractivities)
    {
        $this->useractivities->removeElement($useractivities);
    }

    /**
     * Get useractivities
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getUseractivities()
    {
        return $this->useractivities;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $historiescustomers;


    /**
     * Add historiescustomers
     *
     * @param \sourcinasia\appBundle\Entity\Historycustomer $historiescustomers
     * @return User
     */
    public function addHistoriescustomer(\sourcinasia\appBundle\Entity\Historycustomer $historiescustomers)
    {
        $this->historiescustomers[] = $historiescustomers;

        return $this;
    }

    /**
     * Remove historiescustomers
     *
     * @param \sourcinasia\appBundle\Entity\Historycustomer $historiescustomers
     */
    public function removeHistoriescustomer(\sourcinasia\appBundle\Entity\Historycustomer $historiescustomers)
    {
        $this->historiescustomers->removeElement($historiescustomers);
    }

    /**
     * Get historiescustomers
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getHistoriescustomers()
    {
        return $this->historiescustomers;
    }

    public function getExpireDate()
    {
        return $this->expiresAt;
    }



    /**
     * @var string
     */
    private $token;


    /**
     * Set token
     *
     * @param string $token
     *
     * @return User
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * Get token
     *
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }
    /**
     * @var string
     */
    private $phone;


    /**
     * Set phone
     *
     * @param string $phone
     *
     * @return User
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }
}

src/sourcinasia/appBundle/Entity/saves/Contact.php
<?php

namespace sourcinasia\appBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Contact
 */
class Contact {

    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $phone;

    /**
     * @var string
     */
    private $mobile;

    /**
     * @var string
     */
    private $fax;

    /**
     * @var string
     */
    private $email;

    /**
     * @var string
     */
    private $job;

    /**
     * @var string
     */
    private $qq;

    /**
     * @var string
     */
    private $skype;

    /**
     * @var \sourcinasia\appBundle\Entity\Supplier
     */
    private $supplier;

    /**
     * @var \sourcinasia\appBundle\Entity\Customer
     */
    private $customer;

    /**
     * @var \DateTime
     */
    private $exportdate;

    /**
     * @var integer
     */
    private $exportnbr;

    /**
     * @var integer
     */
    private $exportnbrmax;

    /**
     * @var \sourcinasia\appBundle\Entity\User
     */
    private $user;

    /**
     * @var integer
     */
    private $type;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Contact
     */
    public function setName($name) {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName() {
        return $this->name;
    }

    /**
     * Set phone
     *
     * @param string $phone
     * @return Contact
     */
    public function setPhone($phone) {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string 
     */
    public function getPhone() {
        return $this->phone;
    }

    /**
     * Set mobile
     *
     * @param string $mobile
     * @return Contact
     */
    public function setMobile($mobile) {
        $this->mobile = $mobile;

        return $this;
    }

    /**
     * Get mobile
     *
     * @return string 
     */
    public function getMobile() {
        return $this->mobile;
    }

    /**
     * Set fax
     *
     * @param string $fax
     * @return Contact
     */
    public function setFax($fax) {
        $this->fax = $fax;

        return $this;
    }

    /**
     * Get fax
     *
     * @return string 
     */
    public function getFax() {
        return $this->fax;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Contact
     */
    public function setEmail($email) {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Set job
     *
     * @param string $job
     * @return Contact
     */
    public function setJob($job) {
        $this->job = $job;

        return $this;
    }

    /**
     * Get job
     *
     * @return string 
     */
    public function getJob() {
        return $this->job;
    }

    /**
     * Set qq
     *
     * @param string $qq
     * @return Contact
     */
    public function setQq($qq) {
        $this->qq = $qq;

        return $this;
    }

    /**
     * Get qq
     *
     * @return string 
     */
    public function getQq() {
        return $this->qq;
    }

    /**
     * Set skype
     *
     * @param string $skype
     * @return Contact
     */
    public function setSkype($skype) {
        $this->skype = $skype;

        return $this;
    }

    /**
     * Get skype
     *
     * @return string 
     */
    public function getSkype() {
        return $this->skype;
    }

    /**
     * Set supplier
     *
     * @param \sourcinasia\appBundle\Entity\Supplier $supplier
     * @return Contact
     */
    public function setSupplier(\sourcinasia\appBundle\Entity\Supplier $supplier = null) {
        $this->supplier = $supplier;

        return $this;
    }

    /**
     * Get supplier
     *
     * @return \sourcinasia\appBundle\Entity\Supplier 
     */
    public function getSupplier() {
        return $this->supplier;
    }

    /**
     * Set customer
     *
     * @param \sourcinasia\appBundle\Entity\Customer $customer
     * @return Contact
     */
    public function setCustomer(\sourcinasia\appBundle\Entity\Customer $customer = null) {
        $this->customer = $customer;

        return $this;
    }

    /**
     * Get customer
     *
     * @return \sourcinasia\appBundle\Entity\Customer 
     */
    public function getCustomer() {
        return $this->customer;
    }

    /**
     * Set user
     *
     * @param \sourcinasia\appBundle\Entity\User $user
     * @return Contact
     */
    public function setUser(\sourcinasia\appBundle\Entity\User $user = null) {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \sourcinasia\appBundle\Entity\User 
     */
    public function getUser() {
        return $this->user;
    }

    /**
     * Set exportdate
     *
     * @param \DateTime $exportdate
     * @return Contact
     */
    public function setExportdate($exportdate) {
        $this->exportdate = $exportdate;

        return $this;
    }

    /**
     * Get exportdate
     *
     * @return \DateTime 
     */
    public function getExportdate() {
        return $this->exportdate;
    }

    /**
     * Set exportnbr
     *
     * @param integer $exportnbr
     * @return Contact
     */
    public function setExportnbr($exportnbr) {
        $this->exportnbr = $exportnbr;

        return $this;
    }

    /**
     * Get exportnbr
     *
     * @return integer 
     */
    public function getExportnbr() {
        return $this->exportnbr;
    }

    /**
     * Set type
     *
     * @param integer $type
     * @return Contact
     */
    public function setType($type) {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return integer 
     */
    public function getType() {
        return $this->type;
    }

    /**
     * Set exportnbrmax
     *
     * @param integer $exportnbrmax
     * @return Customer
     */
    public function setExportnbrmax($exportnbrmax) {
        $this->exportnbrmax = $exportnbrmax;

        return $this;
    }

    /**
     * Get exportnbrmax
     *
     * @return integer 
     */
    public function getExportnbrmax() {
        return $this->exportnbrmax;
    }

}

src/sourcinasia/appBundle/Form/ContactType.php
<?php

namespace sourcinasia\appBundle\Form;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('phone')
            ->add('mobile')
            ->add('fax')
            ->add('email', 'email')
            ->add('exportnbrmax')
            ->add('job')
            ->add('qq')
            ->add('skype')
            ->add('type', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', array(
                'choices' => array(
                    'Admin' => '0',
                    'Agent Co(SOURCINASIA)' => '4',
                    'Saler (Saler mode with PO)' => '1',
                    'Customer (Saler mode)' => '2',
                    'Presentation (Presentation mode)' => '3',
                ), 'attr' => array('class' => 'chzn-select'),
                'choices_as_values' => true
            ))
            ->add('supplier', 'Symfony\Bridge\Doctrine\Form\Type\EntityType', array(
                'class' => 'appBundle:Supplier',
                'choice_label' => 'name',
                'attr' => array('class' => 'chzn-select'),
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.name', 'ASC');
                }
            ))
            ->add('customer', 'Symfony\Bridge\Doctrine\Form\Type\EntityType', array(
                'class' => 'appBundle:Customer',
                'choice_label' => 'name',
                'attr' => array('class' => 'chzn-select'),
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.name', 'ASC');
                }
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'sourcinasia\appBundle\Entity\Contact'
        ));
    }
}

src/sourcinasia/appBundle/Resources/views/Contact/desabonnement.html.twig
{% extends "::base.html.twig" %}

 {% block container %}
     <div class="col-md-4 col-md-offset-4">
         <div class="padded">
             <div class="login box" style="margin-top: 80px;">
                 <div class="box-header">
                     <span class="title">{{ 'DESINSCRIPTION_TITRE'|trans()|raw }} </span>
                 </div>
                 <div class="box-content padded">
                     <table width="100%" cellpadding="0" cellspacing="0" class="container">
                         <tbody>
                         <tr>
                         </tr>
                         <tr>
                             <td valign="top" align="left" class="content formText">
                                 <div id="content">

                                     {% if unsub %}
                                         <div id="unsubThankYouPage" class="contentBox">
                                             <div class="alert" id="unsubTitle">{{ 'DESINSCRIPTION_OK'|trans()|raw }}
                                             </div>

                                             <h3 style="font-size: 16px;">{{ 'DESINSCRIPTION_MESSAGE'|trans()|raw }} </h3>
                                         </div>
                                     {% endif %}

                                     {% if update %}
                                         <div id="unsubThankYouPage" class="contentBox">
                                             <div class="alert" id="unsubTitle">{{ 'DESINSCRIPTION_UPDATEOK'|trans()|raw }} </div>

                                             <h3 style="font-size: 16px;">{{ 'DESINSCRIPTION_UPDATEOKMESSAGE'|trans()|raw }}</h3>
                                         </div>
                                     {% endif %}

                                     {% if not update and not unsub %}
                                         <form id="unsubscribe-reason-form"
                                               action="{{ path('unsuscribe',{'token':token}) }}" method="GET" style="">
                                             <h2>{{ 'DESINSCRIPTION_ACTIONS'|trans()|raw }}:</h2>
                                             <table style="width: 100%;">
                                                 <tr>
                                                     <td><h3 style="font-size: 16px;"> 1- {{ 'DESINSCRIPTION_MODIFIERFREQUENCE'|trans()|raw }}</h3>
                                                         <select name="f" id="f" class="required"
                                                                 style="width: 100%">
                                                             <option value="1">{{ 'DESINSCRIPTION_TOUSLES'|trans()|raw }} {{ 'DESINSCRIPTION_JOUR'|trans()|raw }}</option>
                                                             <option value="3">{{ 'DESINSCRIPTION_TOUSLES'|trans()|raw }} 3 {{ 'DESINSCRIPTION_JOUR'|trans()|raw }}</option>
                                                             <option value="7">{{ 'DESINSCRIPTION_TOUSLES'|trans()|raw }} 7 {{ 'DESINSCRIPTION_JOUR'|trans()|raw }}</option>
                                                             <option value="14">{{ 'DESINSCRIPTION_TOUSLES'|trans()|raw }} 2 {{ 'DESINSCRIPTION_SEMAINE'|trans()|raw }}</option>
                                                             <option value="28" selected>{{ 'DESINSCRIPTION_TOUSLES'|trans()|raw }} 4 semaines</option>
                                                             <option value="56">{{ 'DESINSCRIPTION_TOUSLES'|trans()|raw }} 8 {{ 'DESINSCRIPTION_SEMAINE'|trans()|raw }}</option>
                                                             <option value="84">{{ 'DESINSCRIPTION_TOUSLES'|trans()|raw }} 12 {{ 'DESINSCRIPTION_SEMAINE'|trans()|raw }}</option>
                                                             <option value="144">{{ 'DESINSCRIPTION_TOUSLES'|trans()|raw }}6 {{ 'DESINSCRIPTION_MOIS'|trans()|raw }}</option>
                                                             <option value="365">{{ 'DESINSCRIPTION_TOUSLES'|trans()|raw }} {{ 'DESINSCRIPTION_ANNEE'|trans()|raw }}</option>
                                                         </select>
                                                         <input class="button btn btn-default pull-right" type="submit"
                                                                value="{{ 'DESINSCRIPTION_MODIFIERFREQ'|trans()|raw }}"
                                                                style="margin-top:50px;"></td>
                                                 </tr>
                                             </table>
                                         </form>
                                         <form id="unsubscribe-reason-form"
                                               action="{{ path('unsuscribe',{'token':token}) }}" method="GET" style="">
                                             <table style="width: 100%;">
                                                 <tr>
                                                     <td>
                                                         <hr/>
                                                         <h3 style="font-size: 16px;">2- {{ 'DESINSCRIPTION_DESINCRIPTION'|trans()|raw }}</h3>
                                                         <select name="unsub-reason" id="unsub-reason" size="5"
                                                                 class="required"
                                                                 style="width: 100%">
                                                             <option value="1">{{ 'DESINSCRIPTION_R1'|trans()|raw }}  </option>
                                                             <option value="2">{{ 'DESINSCRIPTION_R2'|trans()|raw }}  </option>
                                                             <option value="3">{{ 'DESINSCRIPTION_R3'|trans()|raw }} </option>
                                                             <option value="4">{{ 'DESINSCRIPTION_R4'|trans()|raw }} </option>
                                                             <option value="5">{{ 'DESINSCRIPTION_R5'|trans()|raw }} </option>
                                                         </select>
                                                         <input type="hidden" name="unsub" value="1"/>
                                                         <input class="button btn btn-default pull-right" type="submit"
                                                                value="{{ 'DESINSCRIPTION_DESINCRIPTION'|trans()|raw }}" style="margin-top:50px;">
                                                     </td>
                                                 </tr>
                                                 <tr>
                                                     <td>
                                                 </tr>
                                             </table>
                                         </form>
                                     {% endif %}
                                 </div>
                                 <br clear="all">
                             </td>
                         </tr>
                         </tbody>
                     </table>
                     <div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
 {% endblock %}

src/sourcinasia/appBundle/Resources/views/Contact/list.html.twig
<table class="table">
    <thead>
    <tr>
        <th>Type</th>
        <th>{{ 'ENTITY_CONTACT_NAME'|trans|raw }}</th>
        <th>{{ 'ENTITY_CONTACT_JOB'|trans|raw }}</th>
        <th>{{ 'ENTITY_CONTACT_PHONE'|trans|raw }}</th>
        <th>{{ 'ENTITY_CONTACT_MOBILE'|trans|raw }}</th>
        <th>{{ 'ENTITY_CONTACT_EMAIL'|trans|raw }}</th>
        <th>{{ 'ENTITY_CONTACT_FAX'|trans|raw }}</th>
        <th>{{ 'ENTITY_CONTACT_QQ'|trans|raw }}</th>
        <th>{{ 'ENTITY_CONTACT_SKYPE'|trans|raw }}</th>
        {% if (customer is defined and is_granted('ROLE_ADMIN')  ) %}
            <th>{{ 'State'|trans|raw }}</th>
            <th>{{ 'Access'|trans|raw }}</th>
        {% endif %}
        <th>{{ 'APPLICATION_ACTIONCOLUMN'|trans|raw }}</th>
    </tr>
    </thead>
    <tbody>
    {% for contact in Contacts %}
        <tr>
            <td>

                {% if (contact.user.id is defined and contact.user.enabled ) %}
                    {% if (contact.type==0) %}
                        <i class="icon-user"></i> Admin {% if (commercialtools is defined and commercialtools) %} reseller {% endif %}
                    {% elseif (contact.type==1) %}
                        <i class="icon-suitcase"></i> Saler  (Saler mode with PO)
                    {% elseif (contact.type==2) %}
                        <i class="icon-shopping-cart"></i> Customer  (Saler mode)
                    {% elseif (contact.type==3) %}
                        <i class="icon-shopping-cart"></i> Presentation (Presentation mode)
                    {% elseif (contact.type==4) %}
                        <i class="icon-suitcase"></i> AgentCo INASIA
                    {% endif %}
                {% else %}
                    Contact
                {% endif %}
            </td>
            <td>{{ contact.name }}</td>
            <td>{{ contact.job }}</td>
            <td>{{ contact.phone }}</td>
            <td>{{ contact.mobile }}</td>
            <td><a href="mailto:{{ contact.email }}">{{ contact.email }}</a></td>
            <td>{{ contact.fax }}</td>
            <td>{{ contact.qq }}</td>
            <td>{{ contact.skype }}</td>
            {% if (customer is defined and (is_granted('ROLE_ADMIN') or is_granted('ROLE_COMMERCIAL'))  ) %}
                <td>
                    {% if (contact.user.id is defined) %}
                        {% if (contact.user.enabled) %}
                            {% if (contact.user.expireDate) %}
                                <span style="margin-right: 10px"
                                      class="label label-{{ contact.user.expireDate < today? 'red' :  'green' }}">DEMO ACCESS {{ contact.user.expireDate<today ? 'expired NO ACCESS' : 'OK' }}</span>
                                <br/>
                                Expire date : {{ contact.user.expireDate|date('d-m-Y') }}<br/>
                                {% if  ( contact.user.expireDate > today ) %}
                                    <a href="{{ path('User_regenerate_password',{'id':contact.id}) }}"
                                       class="btn btn-xs btn-default ConfirmAction">{{ 'ENTITY_CONTACT_GENERATEPASSWORD'|trans|raw }}</a>
                                    <a href="{{ path('block_contact_acess',{'id':contact.id}) }}"
                                       class="btn btn-xs btn-default ConfirmAction">{{ 'ENTITY_CONTACT_BLOCK'|trans|raw }}</a>
                                {% else %}
                                    <a href="{{ path('give_contact_acess',{'id':contact.id,'demo':1}) }}"
                                       class="btn btn-xs btn-default ConfirmAction">{{ 'DEMOACCESS'|trans|raw }}</a>
                                {% endif %}
                                {% if is_granted('ROLE_ADMIN') %}
                                    <a href="{{ path('give_contact_acess',{'id':contact.id,'demo':0}) }}"
                                       class="btn btn-xs btn-default ConfirmAction">{{ 'ENTITY_CONTACT_GIVEACCESS'|trans|raw }}</a>
                                {% endif %}
                            {% else %}
                                <span style="margin-right: 10px" class="label label-blue">ACCESS TO MAKET</span><br/>
                                <a href="{{ path('User_regenerate_password',{'id':contact.id}) }}"
                                   class="btn btn-xs btn-default ConfirmAction">{{ 'ENTITY_CONTACT_GENERATEPASSWORD'|trans|raw }}</a>
                                <a href="{{ path('block_contact_acess',{'id':contact.id}) }}"
                                   class="btn btn-xs btn-default ConfirmAction">{{ 'ENTITY_CONTACT_BLOCK'|trans|raw }}</a>
                            {% endif %}
                            <br/>

                        {% else %}
                            <span style="margin-right: 10px" class="label label-black">NO ACCESS</span>   <br/>
                            {% if is_granted('ROLE_ADMIN') %}
                                <a href="{{ path('give_contact_acess',{'id':contact.id,'demo':0}) }}"
                                   class="btn btn-xs btn-default ConfirmAction">{{ 'ENTITY_CONTACT_GIVEACCESS'|trans|raw }}</a>
                            {% endif %}
                            <a href="{{ path('give_contact_acess',{'id':contact.id,'demo':1}) }}"
                               class="btn btn-xs btn-default ConfirmAction">{{ 'DEMOACCESS'|trans|raw }}</a>
                        {% endif %}
                    {% else %}
                        <span style="margin-right: 10px" class="label label-black">NO ACCESS</span>
                        <br/>
                        {% if is_granted('ROLE_ADMIN') %}
                            <a href="{{ path('give_contact_acess',{'id':contact.id,'demo':0}) }}"
                               class="btn btn-xs btn-default ConfirmAction">{{ 'ENTITY_CONTACT_GIVEACCESS'|trans|raw }}</a>
                        {% endif %}
                        <a href="{{ path('give_contact_acess',{'id':contact.id,'demo':1}) }}"
                           class="btn btn-xs btn-default ConfirmAction">{{ 'DEMOACCESS'|trans|raw }}</a>
                    {% endif %}
                </td>
                <td>
                    {% if (contact.user.id is defined) %}
                        Last access : {{ contact.user.lastlogin|date("d/m/Y") }}<br/>
                        login: {{ contact.user.usernamecanonical }}<br/>
                    {% endif %}
                </td>
            {% endif %}
            <td>
                {% if (is_granted('ROLE_SOURCING') or is_granted('ROLE_COMMERCIAL') ) %}
                    <ul>
                        {{ _.dropdownactions([
                        {'route': path('contact_edit', { 'id': contact.id }) ,'text':'ACTION_EDIT'},
                        {'route': path('contact_delete', { 'id': contact.id }) ,'text':'ACTION_DELETE','confirm':'Confirm ?'}
                        ]) }}
                        {% if (customer is defined) %}
                        {% endif %}
                    </ul>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>