src/sourcinasia/appBundle/Entity/Suppliercategory.php
<?php

namespace sourcinasia\appBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Suppliercategory
 */
class Suppliercategory
{
    /**
     * @var int
     */
    protected $id;

    /**
     * @var string
     */
    protected $title;

    /**
     * @var int
     */
    protected $margin_rate;

    /**
     * @ORM\OneToMany(targetEntity="sourcinasia\appBundle\Entity\Supplier", mappedBy="supplierCategory")
     */
    protected $suppliers;

    /**
     * @var \DateTime
     */
    protected $created_at;

    /**
     * Category constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->title       = null;
        $this->margin_rate = 1;
        $this->created_at  = new \DateTime();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     *
     * @return Suppliercategory
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return int
     */
    public function getMarginRate()
    {
        return $this->margin_rate;
    }

    /**
     * @param int $margin_rate
     *
     * @return Suppliercategory
     */
    public function setMarginRate($margin_rate)
    {
        $this->margin_rate = $margin_rate;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSuppliers()
    {
        return $this->suppliers;
    }

    /**
     * @param $suppliers
     *
     * @return Suppliercategory
     */
    public function setSuppliers($suppliers)
    {
        $this->suppliers = $suppliers;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * @param \DateTime $created_at
     *
     * @return Suppliercategory
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/sourcinasia/appBundle/Form/SuppliercategoryType.php
<?php

namespace sourcinasia\appBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SuppliercategoryType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('title', 'Symfony\Component\Form\Extension\Core\Type\TextType', array(
            'label'    => 'Title',
            'required' => true,
            'attr'     => array(
                'class'       => 'form-control',
                'placeholder' => 'Title',
            )
        ))
        ->add('marginRate', 'Symfony\Component\Form\Extension\Core\Type\NumberType', array(
            'label'    => 'Margin rate',
            'required' => true,
            'attr'     => array(
                'class'       => 'form-control',
                'placeholder' => 'Margin rate',
            )
        ))
        ->add('save', 'Symfony\Component\Form\Extension\Core\Type\SubmitType', array(
            'label' => 'Validation',
            'attr'  => array(
                'class' => 'btn btn-success',
            ),
        ));
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'sourcinasia\appBundle\Entity\Suppliercategory'
        ));
    }
}

src/sourcinasia/appBundle/Controller/SuppliercategoryController.php
<?php

namespace sourcinasia\appBundle\Controller;

use sourcinasia\appBundle\Entity\Supplier;
use sourcinasia\appBundle\Entity\Suppliercategory;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * Class SuppliercategoryController
 * @package sourcinasia\appBundle\Controller
 */
class SuppliercategoryController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        // Nous allons rechercher tous les suppliers categories pour les afficher sur l'index
        $suppliersCategories = $em->getRepository('appBundle:Suppliercategory')->findBy(array(), array('created_at' => 'DESC'));

        return $this->render('appBundle:Suppliercategory:index.html.twig', array(
            'suppliersCategories' => $suppliersCategories
        ));
    }

    /**
     * @param Request $request
     * @param null $supplierCategoryId
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function formAction(Request $request, $supplierCategoryId = null)
    {
        $em = $this->getDoctrine()->getManager();

        // Nous sommes dans le cas d'une édition
        if(!empty($supplierCategoryId)) {
            $supplierCategory = $em->getRepository('appBundle:Suppliercategory')->find($supplierCategoryId);
        } else {
            $supplierCategory = new Suppliercategory();
        }

        if(!$supplierCategory instanceof Suppliercategory) {
            throw $this->createNotFoundException('Impossible to find SupplierCategory');
        }

        $form = $this->createForm('sourcinasia\appBundle\Form\SuppliercategoryType', $supplierCategory);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if($form->isValid()) {
                $em->persist($supplierCategory);
                $em->flush();

                $this->get('session')->getFlashBag()->add('notice', 'Supplier category has been created.');
                return $this->redirectToRoute('suppliercategory');
            } else {
                $this->get('session')->getFlashBag()->add('warning', 'The information are not correct.');
                return $this->redirectToRoute('suppliercategory_new');
            }
        }

        return $this->render('appBundle:Suppliercategory:form.html.twig', array(
            'form'             => $form->createView(),
            'supplierCategory' => $supplierCategory,
        ));
    }

    /**
     * @param Request $request
     * @param Suppliercategory $supplierCategory
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(Request $request, Suppliercategory $supplierCategory)
    {
        if (!$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
            throw $this->createAccessDeniedException();
        }

        $em = $this->getDoctrine()->getManager();

        if (!empty($supplierCategory->getSuppliers())) {
            foreach ($supplierCategory->getSuppliers() as $supplier) {
                /** @var $supplier Supplier */
                $supplier->setSupplierCategory(null);
                $em->persist($supplier);
                $em->flush();
            }
        }

        $em->remove($supplierCategory);
        $em->flush();

        return $this->redirectToRoute('suppliercategory');
    }
}

src/sourcinasia/appBundle/Resources/views/Suppliercategory/form.html.twig
{% extends 'appBundle::layout_site.html.twig' %}

{% block header %}
   {% if supplierCategory.id %}
       {{ _.header({'title':'Edit supplier category','subtitle':'Edit supplier category','ico':'icon-edit','parent':{'title':'Edit supplier category','ico':'icon-globe','url':path('suppliercategory')}}) }}
   {% else %}
       {{ _.header({'title':'Add supplier category','subtitle':'New supplier category','ico':'icon-plus','parent':{'title':'Add supplier category','ico':'icon-globe','url':path('suppliercategory')}}) }}
   {% endif %}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {{ form_start(form) }}
                {{ form_errors(form) }}
                <div class="col-12">
                    <div class="form-group">
                        <label for="firstname">Title</label>
                        {{ form_widget(form.title) }}
                        </div>
                    </div>
                <div class="col-12">
                    <div class="form-group">
                        <label for="firstname">Margin rate</label>
                        {{ form_widget(form.marginRate) }}
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group text-left">
                        {{ form_widget(form.save) }}
                    </div>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

src/sourcinasia/appBundle/Resources/views/Suppliercategory/index.html.twig
{% extends "appBundle::layout_site.html.twig" %}

{% block header %}
    {{ _.header({'title':'Supplier category','subtitle':'List of suppliers categories','ico':'icon-folder-close','parent':{'title':'Supplier category','ico':'icon-globe','url':path('suppliercategory')}}) }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row text-right">
            <div class="col-xs-12">
                <a href="{{ path('suppliercategory_new') }}" type="button" class="btn btn-success"><i class="icon-plus"></i>&nbsp;Supplier category</a>
            </div>
        </div>

        <table class="table table-striped" id="suppliersCategoriesList">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Margin rate</th>
                    <th>Created at</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for supplierCategory in suppliersCategories %}
                    <tr>
                        <td class="vce">{{ supplierCategory.id }}</td>
                        <td>{{ supplierCategory.title }}</td>
                        <td>{{ supplierCategory.marginRate }}</td>
                        <td>{{ supplierCategory.createdAt | date('d/m/Y H:i:s') }}</td>
                        <td>
                            <a href="{{ path('suppliercategory_edit', {supplierCategoryId: supplierCategory.id}) }}" type="button" class="btn btn-primary"><i class="icon-edit"></i></a>
                            <a href="{{ path('suppliercategory_delete', {supplierCategory: supplierCategory.id}) }}" type="button" class="btn btn-danger"><i class="icon-trash"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

src/sourcinasia/appBundle/Resources/views/Suppliercategory/list.html.twig
<table class="table">
	<thead>
		<tr>
			<th>{{'ENTITY_SUPPLIERCOMMENT_DATE'|trans }} </th>
			<th>{{'ENTITY_SUPPLIERCOMMENT_USER'|trans }} </th>
			<th>{{'ENTITY_SUPPLIERCOMMENT_TITLE'|trans }} </th>
			<th>{{'ENTITY_SUPPLIERCOMMENT_COMMENTS'|trans }} </th>
			<th>{{'APPLICATION_ACTIONCOLUMN'|trans }}</th>
		</tr>
	</thead>
	<tbody>
		{% for Suppliercomment in Suppliercomments %}
		<tr>
			<td>{{ Suppliercomment.date|date("d/m/Y") }}</td>
			<td>{{ Suppliercomment.user.username }}</td>
			<td>{{ Suppliercomment.title }}</td>
			<td>{{ Suppliercomment.comments }}</td>
			<td>
				{{_.dropdownactions([
				{'route': path('suppliercomment_edit', { 'idsupplier': Suppliercomment.id }) ,'text':'ACTION_EDIT','ico':'icon-edit'},
				{'route': path('suppliercomment_delete', { 'id': Suppliercomment.id }) ,'text':'ACTION_DELETE','confirm':''}  
				])}}
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>